# Generated by Django 5.0.6 on 2024-05-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('identity', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('account', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('ctfc', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
