# Generated by Django 4.2.13 on 2024-05-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_customer_delete_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
