# Generated by Django 4.2.13 on 2024-05-31 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
