# Generated by Django 4.2.13 on 2024-05-31 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="username",
        ),
    ]
