# Generated by Django 5.0.6 on 2024-06-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotations',
            old_name='Buyamt',
            new_name='buyamt',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stmp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='snum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock.stock'),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='sprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='tstmp',
            field=models.DateTimeField(),
        ),
    ]
